version: "3.3"

services:

  globus:
    image: globus     
    build: ./globus
    container_name: globus   
    ports:
      - 9098:9098
    deploy:
      replicas: 1
    networks:
      - mnet    
     
networks:
  mnet:
    driver: bridge
